server:
  port: 9099
  
spring:
  application:
    name: user-hystrix
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8084/eureka/